name: frontend
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  equations: ^5.0.2
  expressions: ^0.2.5+1
  fl_chart: ^0.68.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.10
  flutter_svg: ^2.0.10+1
  material_design_icons_flutter: ^7.0.7296
  math_expressions: ^2.5.0
  math_keyboard: ^0.2.1
  pdf: ^3.10.8
  petitparser: any
  printing: ^5.12.0
  syncfusion_flutter_charts: ^25.2.4
dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  msix: ^3.16.7

dependency_overrides:
  intl: 0.19.0

flutter:
  uses-material-design: true
  assets:
    - assets/

  fonts:
    - family: Anta
      fonts:
        - asset: assets/fonts/Anta-Regular.ttf
    - family: Noto
      fonts:
        - asset: assets/fonts/math.ttf

msix_config:
  display_name: JF
  publisher_display_name: JF Solver
  identity_name: com.example.frontend
  msix_version: 1.0.0.0
  logo_path: C:\Users\monda\OneDrive\Desktop\fyp\frontend\assets\logo\logo.png
  capabilities: internetClient, location
